app/src/Entity/Classes.php
<?php

namespace App\Entity;

use App\Repository\ClassesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ClassesRepository::class)]
class Classes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToMany(mappedBy: 'classe', targetEntity: user::class)]
    private Collection $classe;

    #[ORM\Column(length: 5)]
    private ?string $classe_name = null;

    public function __construct()
    {
        $this->classe = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, user>
     */
    public function getClasse(): Collection
    {
        return $this->classe;
    }

    public function addClasse(user $classe): self
    {
        if (!$this->classe->contains($classe)) {
            $this->classe->add($classe);
            $classe->setClasse($this);
        }

        return $this;
    }

    public function removeClasse(user $classe): self
    {
        if ($this->classe->removeElement($classe)) {
            // set the owning side to null (unless already changed)
            if ($classe->getClasse() === $this) {
                $classe->setClasse(null);
            }
        }

        return $this;
    }

    public function getClasseName(): ?string
    {
        return $this->classe_name;
    }

    public function setClasseName(string $classe_name): self
    {
        $this->classe_name = $classe_name;

        return $this;
    }
}

app/src/Entity/User.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Tools\Pagination\Paginator;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
#[ApiResource]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    private ?string $surname = null;

    #[ORM\Column(length: 100)]
    private ?string $mail = null;

    #[ORM\Column(length: 50)]
    private ?string $pseudo = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: NoteControle::class)]
    private Collection $noteControles;

    #[ORM\ManyToOne(inversedBy: 'classe')]
    private ?Classes $classe = null;

    public function __construct()
    {
        $this->noteControles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * @return Collection<int, NoteControle>
     */
    public function getNoteControles(): Collection
    {
        return $this->noteControles;
    }

    public function addNoteControle(NoteControle $noteControle): self
    {
        if (!$this->noteControles->contains($noteControle)) {
            $this->noteControles->add($noteControle);
            $noteControle->setUser($this);
        }

        return $this;
    }

    public function removeNoteControle(NoteControle $noteControle): self
    {
        if ($this->noteControles->removeElement($noteControle)) {
            // set the owning side to null (unless already changed)
            if ($noteControle->getUser() === $this) {
                $noteControle->setUser(null);
            }
        }

        return $this;
    }

    public function getClasse(): ?Classes
    {
        return $this->classe;
    }

    public function setClasse(?Classes $classe): self
    {
        $this->classe = $classe;

        return $this;
    }

}

app/src/Controller/ClasseController.php
<?php

namespace App\Controller;

use App\Entity\Matiere;
use App\Entity\User;
use App\Entity\NoteControle;
use App\Entity\Classes;
use App\Form\NoteFormType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormTypeInterface;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Repository\UserRepository;
use Twig\Environment;

class ClasseController extends AbstractController
{
    #[Route('/classe', name: 'app_classe')]
    public function index(Environment $twig, UserRepository $userRepository): Response
    {
        $users = $userRepository->createQueryBuilder('user')
            ->leftJoin('user.classe', 'classe')
            ->orderBy('classe.id', 'ASC')
            ->getQuery()
            ->getResult();

        return new Response($twig->render('classe/classe.html.twig', [
            'users' => $users,
        ]));
    }
}

app/templates/classe/classe.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {% if app.user.userIdentifier is defined %}!
{% endif %}
{% endblock %}

{% block body %}
    {% include "menu/navbar_index.html.twig" %}
    {% include "menu/sidebar_index.html.twig" %}
    {% include "classe/contain.html.twig" %}
{% endblock %}

app/templates/classe/contain.html.twig
 {% block stylesheets %}
    <link href="{{ asset('html/contain_mark.css') }}" rel="stylesheet" /> 
{% endblock %}
    <div class="page-wrapper">
        <div class="container-fluid">
            <div class="row tableau">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">Students Marks</h5>
                            <h6 class="card-subtitle"></h6>
                                {% include "classe/eleve_classe.html.twig" %}    
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    </div>

app/templates/classe/eleve_classe.html.twig
{% block body %}
    <div class="table-responsive">
        <table class="table">
            <tbody> 
                <tr>
                    <th id="t">Class</th>
                    <th id="t">Surname</th>
                    <th id="t">Name</th>
                    <th id="t">mail</th>
                </tr>
                {% for user in users %}
                    <tr>
                        <td id="th5"><a href="{{ path('app_moyenne', { ClasseName: user.classe.ClasseName}) }}">{{ user.classe.classeName }}</a></td>
                        <td id="th1">{{ user.surname }}</td>
                        <td id="th2">{{ user.username }}</td>
                        <td id="th5">{{ user.mail }}</td> 
                    </tr>
                {% endfor %}
            </tbody>   
        </table>
    </div>
{% endblock %}